### PR TITLE
Added PAM_API_KEY as a new key to be stored in publishing clusters

### PR DESCRIPTION
**Pull request by tosan88**
As part of productionizing Notifications-Push, we need to supply a valid apiKey on requests to NP service. 
This change is needed for PAM.

**Note**: LastPass notes `TEST Publishing cluster provisioning setup` and `PROD Publishing cluster provisioning setup` were updated, but commented out for now

### CODE REVIEW

**Comment by tosan88** [comment]
[upp-provisioner - add etcd key for PAM](https://trello.com/c/MN1kewaZ/33-upp-provisioner-add-etcd-key-for-pam)

**Comment by efinlay24** [comment]
Will this key be different between clusters?

If it's always consistent (or if there's only 2 keys, one for test and one for prod), it may make more sense to put it in the vault instead of an environment variable.

If this key will be different between every cluster, then an environment variable is fine. :)

**Comment by tosan88** [comment]
@efinlay24 I'd expect to be only 2 different keys - one for test.api.ft.com and one for api.ft.com

**Comment by efinlay24** [comment]
Oh, we've not migrated delivery and publishing to the new accounts yet, so we don't have separate Ansible vault files for test and prod at the moment.

Fair enough, env variable is fine then. :)

**Pull request merged**
